### ISSUE TITLE
Adding support for certain missing aws resources

### ISSUE THREAD

**Issue by juno-yu** [GoogleCloudPlatform/terraformer#458]
There are some missing resources for api provider comparing this repo's README & https://www.terraform.io/docs/providers/aws/

Below is NOT a complete list, but what I spotted from the list. 
I might PR to add support for some of below to support generating tf files from existing aws resources for infrastructure as code practice.

- [ ] Appsync (#452 , not covering all resources yet)
- [ ] Cognito (#454 , not covering all resources yet) 
- [ ] Pinpoint 
- [x] SWF  (#459 )
- [x] Step Function SFN (#461 )
- [x] XRay (#462)
- [ ] Service Quotas
- [ ] Cost and Usage Report
- [ ] Transfer 
- [ ] MQ
- [ ] Shield (this one is a bit expensive for individual contributor not using it to test with , help wanted from those who using it)
