### ISSUE TITLE
Adding support for certain azurerm resources

### ISSUE THREAD

**Issue by juno-yu** [GoogleCloudPlatform/terraformer#543]
(WIP, will complement per some of my usages & update tracking merged PRs)
(per comparison with https://www.terraform.io/docs/providers/azurerm/r/resource_group.html 20200706 , excluding `data sources` items)

Base Resources

-  [x] azurerm_resource_group

Analysis Services Resources

-  [x] azurerm_analysis_services_server

API Management Resources

-  [ ] azurerm_api_management
-  [ ] azurerm_api_management_api
-  [ ] azurerm_api_management_api_operation
-  [ ] azurerm_api_management_api_operation_policy
-  [ ] azurerm_api_management_api_policy
-  [ ] azurerm_api_management_api_schema
-  [ ] azurerm_api_management_subscription
-  [ ] azurerm_api_management_api_version_set
-  [ ] azurerm_api_management_authorization_server
-  [ ] azurerm_api_management_backend
-  [ ] azurerm_api_management_certificate
-  [ ] azurerm_api_management_diagnostic
-  [ ] azurerm_api_management_group
-  [ ] azurerm_api_management_group_user
-  [ ] azurerm_api_management_identity_provider_aad
-  [ ] azurerm_api_management_identity_provider_facebook
-  [ ] azurerm_api_management_identity_provider_google
-  [ ] azurerm_api_management_identity_provider_twitter
-  [ ] azurerm_api_management_logger
-  [ ] azurerm_api_management_openid_connect_provider
-  [ ] azurerm_api_management_product
-  [ ] azurerm_api_management_product_api
-  [ ] azurerm_api_management_identity_provider_microsoft
-  [ ] azurerm_api_management_product_group
-  [ ] azurerm_api_management_named_value
-  [ ] azurerm_api_management_product_policy
-  [ ] azurerm_api_management_property
-  [ ] azurerm_api_management_user

App Configuration

-  [ ] azurerm_app_configuration

App Service (Web Apps) Resources

-  [x] azurerm_app_service
-  [ ] azurerm_app_service_active_slot
-  [ ] azurerm_app_service_certificate
-  [ ] azurerm_app_service_certificate_order
-  [ ] azurerm_app_service_custom_hostname_binding
-  [ ] azurerm_app_service_environment
-  [ ] azurerm_app_service_hybrid_connection
-  [ ] azurerm_app_service_plan
-  [ ] azurerm_app_service_slot
-  [ ] azurerm_app_service_source_control_token
-  [ ] azurerm_app_service_virtual_network_swift_connection
-  [ ] azurerm_function_app
-  [ ] azurerm_function_app_slot

Application Insights Resources

-  [ ] azurerm_application_insights
-  [ ] azurerm_application_insights_api_key
-  [ ] azurerm_application_insights_analytics_item
-  [ ] azurerm_application_insights_web_test

Spring Cloud

-  [ ] azurerm_spring_cloud_app
-  [ ] azurerm_spring_cloud_service

Authorization Resources

-  [ ] azurerm_role_assignment
-  [ ] azurerm_role_definition
-  [ ] azurerm_user_assigned_identity

Automation Resources

-  [ ] azurerm_automation_account
-  [ ] azurerm_automation_certificate
-  [ ] azurerm_automation_credential
-  [ ] azurerm_automation_dsc_configuration
-  [ ] azurerm_automation_dsc_nodeconfiguration
-  [ ] azurerm_automation_job_schedule
-  [ ] azurerm_automation_module
-  [ ] azurerm_automation_runbook
-  [ ] azurerm_automation_schedule
-  [ ] azurerm_automation_variable_bool
-  [ ] azurerm_automation_variable_datetime
-  [ ] azurerm_automation_variable_int
-  [ ] azurerm_automation_variable_string

Backup Resources

-  [ ] azurerm_backup_container_storage_account
-  [ ] azurerm_backup_policy_file_share
-  [ ] azurerm_backup_policy_vm
-  [ ] azurerm_backup_protected_file_share
-  [ ] azurerm_backup_protected_vm

Batch Resources

-  [ ] azurerm_batch_account
-  [ ] azurerm_batch_application
-  [ ] azurerm_batch_certificate
-  [ ] azurerm_batch_pool

Blueprints Resources

-  [ ] azurerm_blueprint_assignment

Bot Resources

-  [ ] azurerm_bot_channel_email
-  [ ] azurerm_bot_channel_ms_teams
-  [ ] azurerm_bot_channel_slack
-  [ ] azurerm_bot_channel_directline
-  [ ] azurerm_bot_channels_registration
-  [ ] azurerm_bot_connection
-  [ ] azurerm_bot_web_app

CDN Resources

-  [ ] azurerm_cdn_endpoint
-  [ ] azurerm_cdn_profile

Cognitive Services Resources

-  [ ] azurerm_cognitive_account

Compute Resources

-  [ ] azurerm_availability_set
-  [ ] azurerm_dedicated_host
-  [ ] azurerm_dedicated_host_group
-  [ ] azurerm_disk_encryption_set
-  [ ] azurerm_image
-  [x] azurerm_linux_virtual_machine
-  [ ] azurerm_linux_virtual_machine_scale_set
-  [ ] azurerm_managed_application_definition
-  [ ] azurerm_managed_application
-  [x] azurerm_managed_disk
-  [ ] azurerm_marketplace_agreement
-  [ ] azurerm_proximity_placement_group
-  [ ] azurerm_shared_image
-  [ ] azurerm_shared_image_gallery
-  [ ] azurerm_shared_image_version
-  [ ] azurerm_snapshot
-  [x] azurerm_virtual_machine
-  [ ] azurerm_virtual_machine_data_disk_attachment
-  [ ] azurerm_virtual_machine_extension
-  [x] azurerm_virtual_machine_scale_set (#548)
-  [ ] azurerm_virtual_machine_scale_set_extension
-  [ ] azurerm_orchestrated_virtual_machine_scale_set
-  [x] azurerm_windows_virtual_machine
-  [ ] azurerm_windows_virtual_machine_scale_set

Container Resources

-  [x] azurerm_container_group (#553)
-  [x] azurerm_container_registry (#553)
-  [x] azurerm_container_registry_webhook (#553)
-  [ ] azurerm_kubernetes_cluster
-  [ ] azurerm_kubernetes_cluster_node_pool

CosmosDB (DocumentDB) Resources

-  [x] azurerm_cosmosdb_account (#542)
-  [ ] azurerm_cosmosdb_cassandra_keyspace
-  [ ] azurerm_cosmosdb_gremlin_database
-  [ ] azurerm_cosmosdb_gremlin_graph
-  [ ] azurerm_cosmosdb_mongo_collection
-  [ ] azurerm_cosmosdb_mongo_database
-  [x] azurerm_cosmosdb_sql_container (#542)
-  [x] azurerm_cosmosdb_sql_database (#542)
-  [x] azurerm_cosmosdb_table (#542)

Cost Management Resources

-  [ ] azurerm_cost_management_export_resource_group
-  [ ] Custom Providers
-  [ ] azurerm_custom_provider

Database Resources

-  [x] azurerm_mariadb_configuration
-  [x] azurerm_mariadb_database
-  [x] azurerm_mariadb_firewall_rule
-  [x] azurerm_mariadb_server
-  [x] azurerm_mariadb_virtual_network_rule
-  [x] azurerm_mysql_configuration
-  [x] azurerm_mysql_database
-  [x] azurerm_mysql_firewall_rule
-  [x] azurerm_mysql_server
-  [x] azurerm_mysql_virtual_network_rule
-  [ ] azurerm_postgresql_active_directory_administrator
-  [x] azurerm_postgresql_configuration
-  [x] azurerm_postgresql_database
-  [x] azurerm_postgresql_firewall_rule
-  [x] azurerm_postgresql_server
-  [x] azurerm_postgresql_virtual_network_rule
-  [x] azurerm_sql_database
-  [ ] azurerm_mssql_database
-  [x] azurerm_sql_active_directory_administrator
-  [x] azurerm_sql_elasticpool
-  [ ] azurerm_mssql_elasticpool
-  [x] azurerm_sql_failover_group
-  [x] azurerm_sql_firewall_rule
-  [x] azurerm_sql_server
-  [x] azurerm_sql_virtual_network_rule
-  [ ] azurerm_mssql_server
-  [ ] azurerm_mssql_server_security_alert_policy
-  [ ] azurerm_mssql_server_vulnerability_assessment
-  [ ] azurerm_mssql_database_vulnerability_assessment_rule_baseline
-  [ ] azurerm_mssql_virtual_machine

Database Migration Resources

-  [ ] azurerm_database_migration_project
-  [ ] azurerm_database_migration_service

Databricks Resources

-  [ ] azurerm_databricks_workspace

Data Explorer Resources

-  [ ] azurerm_kusto_cluster
-  [ ] azurerm_kusto_cluster_principal_assignment
-  [ ] azurerm_kusto_database
-  [ ] azurerm_kusto_database_principal
-  [ ] azurerm_kusto_eventhub_data_connection

Data Factory Resources

-  [ ] azurerm_data_factory
-  [ ] azurerm_data_factory_dataset_mysql
-  [ ] azurerm_data_factory_dataset_postgresql
-  [ ] azurerm_data_factory_dataset_sql_server_table
-  [ ] azurerm_data_factory_integration_runtime_managed
-  [ ] azurerm_data_factory_integration_runtime_self_hosted
-  [ ] azurerm_data_factory_pipeline
-  [ ] azurerm_data_factory_linked_service_data_lake_storage_gen2
-  [ ] azurerm_data_factory_linked_service_key_vault
-  [ ] azurerm_data_factory_linked_service_mysql
-  [ ] azurerm_data_factory_linked_service_postgresql
-  [ ] azurerm_data_factory_linked_service_sql_server
-  [ ] azurerm_data_factory_trigger_schedule

Data Lake Resources

-  [ ] azurerm_data_lake_analytics_account
-  [ ] azurerm_data_lake_analytics_firewall_rule
-  [ ] azurerm_data_lake_store
-  [ ] azurerm_data_lake_store_file
-  [ ] azurerm_data_lake_store_firewall_rule

Data Share Resources

-  [ ] azurerm_data_share
-  [ ] azurerm_data_share_account
-  [ ] azurerm_data_share_dataset_blob_storage

DevSpace Resources

-  [ ] azurerm_devspace_controller

Dev Test Resources

-  [ ] azurerm_dev_test_global_vm_shutdown_schedule
-  [ ] azurerm_dev_test_lab
-  [ ] azurerm_dev_test_linux_virtual_machine
-  [ ] azurerm_dev_test_policy
-  [ ] azurerm_dev_test_schedule
-  [ ] azurerm_dev_test_virtual_network
-  [ ] azurerm_dev_test_windows_virtual_machine

DNS Resources

-  [x] azurerm_dns_a_record (#554)
-  [x] azurerm_dns_aaaa_record (#554)
-  [x] azurerm_dns_caa_record (#554)
-  [x] azurerm_dns_cname_record (#554)
-  [x] azurerm_dns_mx_record (#554)
-  [x] azurerm_dns_ns_record (#554)
-  [x] azurerm_dns_ptr_record (#554)
-  [x] azurerm_dns_srv_record (#554)
-  [x] azurerm_dns_txt_record (#554)
-  [x] azurerm_dns_zone (#554)

Front Door Resources

-  [ ] azurerm_frontdoor
-  [ ] azurerm_frontdoor_firewall_policy

HDInsight Resources

-  [ ] azurerm_hdinsight_hadoop_cluster
-  [ ] azurerm_hdinsight_hbase_cluster
-  [ ] azurerm_hdinsight_kafka_cluster
-  [ ] azurerm_hdinsight_interactive_query_cluster
-  [ ] azurerm_hdinsight_ml_services_cluster
-  [ ] azurerm_hdinsight_rserver_cluster
-  [ ] azurerm_hdinsight_spark_cluster
-  [ ] azurerm_hdinsight_storm_cluster

Healthcare API Resources

-  [ ] azurerm_healthcare_service

IoTCentral Application Resources

-  [ ] azurerm_iotcentral_application

IoT Hub Resources

-  [ ] azurerm_iothub
-  [ ] azurerm_iothub_consumer_group
-  [ ] azurerm_iothub_dps
-  [ ] azurerm_iothub_dps_certificate
-  [ ] azurerm_iothub_dps_shared_access_policy
-  [ ] azurerm_iothub_endpoint_eventhub
-  [ ] azurerm_iothub_endpoint_servicebus_queue
-  [ ] azurerm_iothub_endpoint_servicebus_topic
-  [ ] azurerm_iothub_endpoint_storage_container
-  [ ] azurerm_iothub_fallback_route
-  [ ] azurerm_iothub_route
-  [ ] azurerm_iothub_shared_access_policy
-  [ ] IoT Time Series Insights
-  [ ] azurerm_iot_time_series_insights_access_policy
-  [ ] azurerm_iot_time_series_insights_standard_environment
-  [ ] azurerm_iot_time_series_insights_reference_data_set

Key Vault Resources

-  [x] azurerm_key_vault (#547)
-  [ ] azurerm_key_vault_access_policy
-  [ ] azurerm_key_vault_certificate
-  [ ] azurerm_key_vault_key
-  [ ] azurerm_key_vault_secret

Load Balancer Resources

-  [x] azurerm_lb (#550)
-  [x] azurerm_lb_backend_address_pool (#550)
-  [ ] azurerm_lb_rule
-  [ ] azurerm_lb_outbound_rule
-  [x] azurerm_lb_nat_rule (#550)
-  [ ] azurerm_lb_nat_pool
-  [x] azurerm_lb_probe (#550)

Log Analytics Resources

-  [ ] azurerm_log_analytics_datasource_windows_event
-  [ ] azurerm_log_analytics_datasource_windows_performance_counter
-  [ ] azurerm_log_analytics_linked_service
-  [ ] azurerm_log_analytics_solution
-  [ ] azurerm_log_analytics_workspace

Logic App Resources

-  [ ] azurerm_logic_app_action_custom
-  [ ] azurerm_logic_app_action_http
-  [ ] azurerm_logic_app_integration_account
-  [ ] azurerm_logic_app_trigger_custom
-  [ ] azurerm_logic_app_trigger_http_request
-  [ ] azurerm_logic_app_trigger_recurrence
-  [ ] azurerm_logic_app_workflow

Machine Learning Resources

-  [ ] azurerm_machine_learning_workspace

Maintenance Resources

-  [ ] azurerm_maintenance_assignment_dedicated_host
-  [ ] azurerm_maintenance_assignment_virtual_machine
-  [ ] azurerm_maintenance_configuration

Management Resources

-  [ ] azurerm_management_lock
-  [ ] azurerm_management_group

Maps Resources

-  [ ] azurerm_maps_account

Media Resources

-  [ ] azurerm_media_services_account
-  [ ] Mixed Reality
-  [ ] azurerm_spatial_anchors_account

Messaging Resources

-  [ ] azurerm_eventgrid_domain
-  [ ] azurerm_eventgrid_domain_topic
-  [ ] azurerm_eventgrid_event_subscription
-  [ ] azurerm_eventgrid_topic
-  [ ] azurerm_eventhub
-  [ ] azurerm_eventhub_authorization_rule
-  [ ] azurerm_eventhub_namespace_disaster_recovery_config
-  [ ] azurerm_eventhub_cluster
-  [ ] azurerm_eventhub_consumer_group
-  [ ] azurerm_eventhub_namespace
-  [ ] azurerm_eventhub_namespace_authorization_rule
-  [ ] azurerm_notification_hub
-  [ ] azurerm_notification_hub_authorization_rule
-  [ ] azurerm_notification_hub_namespace
-  [ ] azurerm_relay_hybrid_connection
-  [ ] azurerm_relay_namespace
-  [ ] azurerm_servicebus_namespace
-  [ ] azurerm_servicebus_namespace_authorization_rule
-  [ ] azurerm_servicebus_namespace_network_rule_set
-  [ ] azurerm_servicebus_queue
-  [ ] azurerm_servicebus_queue_authorization_rule
-  [ ] azurerm_servicebus_subscription
-  [ ] azurerm_servicebus_subscription_rule
-  [ ] azurerm_servicebus_topic
-  [ ] azurerm_servicebus_topic_authorization_rule
-  [ ] azurerm_signalr_service

Monitor Resources

-  [ ] azurerm_monitor_action_group
-  [ ] azurerm_monitor_action_rule_action_group
-  [ ] azurerm_monitor_action_rule_suppression
-  [ ] azurerm_monitor_activity_log_alert
-  [ ] azurerm_monitor_autoscale_setting
-  [ ] azurerm_monitor_diagnostic_setting
-  [ ] azurerm_monitor_log_profile
-  [ ] azurerm_monitor_metric_alert
-  [ ] azurerm_monitor_scheduled_query_rules_alert
-  [ ] azurerm_monitor_scheduled_query_rules_log

Network Resources

-  [ ] azurerm_application_gateway
-  [ ] azurerm_application_security_group
-  [ ] azurerm_bastion_host
-  [ ] azurerm_network_ddos_protection_plan
-  [ ] azurerm_express_route_circuit
-  [ ] azurerm_express_route_circuit_authorization
-  [ ] azurerm_express_route_circuit_peering
-  [ ] azurerm_express_route_gateway
-  [ ] azurerm_firewall
-  [ ] azurerm_firewall_application_rule_collection
-  [ ] azurerm_firewall_nat_rule_collection
-  [ ] azurerm_firewall_network_rule_collection
-  [ ] azurerm_local_network_gateway
-  [ ] azurerm_nat_gateway
-  [ ] azurerm_nat_gateway_public_ip_association
-  [x] azurerm_network_interface
-  [ ] azurerm_network_interface_application_gateway_backend_address_pool_association
-  [ ] azurerm_network_interface_application_security_group_association
-  [ ] azurerm_network_interface_backend_address_pool_association
-  [ ] azurerm_network_interface_nat_rule_association
-  [ ] azurerm_network_interface_security_group_association
-  [ ] azurerm_network_packet_capture
-  [ ] azurerm_network_profile
-  [x] azurerm_network_security_group
-  [ ] azurerm_network_security_rule
-  [ ] azurerm_network_watcher
-  [ ] azurerm_network_watcher_flow_log
-  [ ] azurerm_packet_capture
-  [ ] azurerm_point_to_site_vpn_gateway
-  [ ] azurerm_private_link_service
-  [ ] azurerm_private_endpoint
-  [x] azurerm_public_ip (#558)
-  [x] azurerm_public_ip_prefix (#558)
-  [ ] azurerm_route
-  [ ] azurerm_route_table
-  [ ] azurerm_subnet
-  [ ] azurerm_subnet_nat_gateway_association
-  [ ] azurerm_subnet_network_security_group_association
-  [ ] azurerm_subnet_route_table_association
-  [ ] azurerm_traffic_manager_endpoint
-  [ ] azurerm_traffic_manager_profile
-  [ ] azurerm_virtual_hub
-  [ ] azurerm_virtual_hub_connection
-  [x] azurerm_virtual_network
-  [ ] azurerm_virtual_network_gateway
-  [ ] azurerm_virtual_network_gateway_connection
-  [ ] azurerm_virtual_network_peering
-  [ ] azurerm_virtual_wan
-  [ ] azurerm_vpn_gateway
-  [ ] azurerm_vpn_server_configuration
-  [ ] azurerm_web_application_firewall_policy

NetApp Resources

-  [ ] azurerm_netapp_account
-  [ ] azurerm_netapp_pool
-  [ ] azurerm_netapp_volume
-  [ ] azurerm_netapp_snapshot

Policy Resources

-  [ ] azurerm_policy_assignment
-  [ ] azurerm_policy_definition
-  [ ] azurerm_policy_remediation
-  [ ] azurerm_policy_set_definition

Portal Resources

-  [ ] azurerm_dashboard

PowerBI Resources

-  [ ] azurerm_powerbi_embedded

Private DNS Resources

-  [x] azurerm_private_dns_a_record (#555)
-  [x] azurerm_private_dns_aaaa_record (#555)
-  [x] azurerm_private_dns_cname_record (#555)
-  [x] azurerm_private_dns_mx_record (#555)
-  [x] azurerm_private_dns_ptr_record (#555)
-  [x] azurerm_private_dns_srv_record (#555)
-  [x] azurerm_private_dns_txt_record (#555)
-  [x] azurerm_private_dns_zone (#555)
-  [x] azurerm_private_dns_zone_virtual_network_link (#555)

Recovery Services

-  [ ] azurerm_recovery_services_vault

Redis Resources

-  [x] azurerm_redis_cache
-  [ ] azurerm_redis_firewall_rule

Search Resources

-  [ ] azurerm_search_service

Security Center Resources

-  [ ] azurerm_advanced_threat_protection
-  [x] azurerm_security_center_contact
-  [x] azurerm_security_center_subscription_pricing
-  [ ] azurerm_security_center_workspace

Sentinel Resources

-  [ ] azurerm_sentinel_alert_rule_ms_security_incident
-  [ ] azurerm_sentinel_alert_rule_scheduled

Service Fabric Resources

-  [ ] azurerm_service_fabric_cluster

Site Recovery Resources

-  [ ] azurerm_site_recovery_fabric
-  [ ] azurerm_site_recovery_network_mapping
-  [ ] azurerm_site_recovery_protection_container_mapping
-  [ ] azurerm_site_recovery_protection_container
-  [ ] azurerm_site_recovery_replicated_vm
-  [ ] azurerm_site_recovery_replication_policy

Stream Analytics Resources

-  [ ] azurerm_stream_analytics_job
-  [ ] azurerm_stream_analytics_function_javascript_udf
-  [ ] azurerm_stream_analytics_output_blob
-  [ ] azurerm_stream_analytics_output_mssql
-  [ ] azurerm_stream_analytics_output_eventhub
-  [ ] azurerm_stream_analytics_output_servicebus_queue
-  [ ] azurerm_stream_analytics_output_servicebus_topic
-  [ ] azurerm_stream_analytics_reference_input_blob
-  [ ] azurerm_stream_analytics_stream_input_blob
-  [ ] azurerm_stream_analytics_stream_input_eventhub
-  [ ] azurerm_stream_analytics_stream_input_iothub

Storage Resources

-  [ ] azurerm_hpc_cache
-  [ ] azurerm_hpc_cache_nfs_target
-  [ ] azurerm_hpc_cache_blob_target
-  [x] azurerm_storage_account
-  [ ] azurerm_storage_account_customer_managed_key
-  [ ] azurerm_storage_account_network_rules
-  [x] azurerm_storage_blob
-  [x] azurerm_storage_container
-  [ ] azurerm_storage_data_lake_gen2_filesystem
-  [ ] azurerm_storage_management_policy
-  [ ] azurerm_storage_queue
-  [ ] azurerm_storage_share
-  [ ] azurerm_storage_share_directory
-  [ ] azurerm_storage_table
-  [ ] azurerm_storage_table_entity

Template Resources

-  [ ] azurerm_template_deployment

**Comment by boldandbusted** [comment]
Just for ease-of-reference, here's the main repository of Azure REST API docs: https://docs.microsoft.com/en-us/rest/api/azure/ :)
